### PR TITLE
Add Lua scripts for removing annotations

### PR DESCRIPTION
**Pull request by mkoncek**
**Requires: rpm >= 4.18** (for `/usr/bin/rpmlua`)

Tested on package `guava`:
```
./java-utils/java_remove_symbols.lua -a guava-31.0.1 -p GwtCompatible GwtIncompatible VisibleForTesting Immutable CompatibleWith ReflectionSupport GuardedBy DoNotCall Beta DoNotMock Nullable MonotonicNonNull WeakOuter CanIgnoreReturnValue NonNull J2ObjCIncompatible LazyInit RetainedWith ForOverride Weak MustBeClosed CheckReturnValue OverridingMethodsMustInvokeSuper InlineMe InlineMeValidationDisabled
```

Diff after using it on the Fedora package `classpathless-compiler`:
```diff
-find -name '*.java' -exec sed -i '/@SuppressFBWarnings\|import edu\.umd\.cs\.findbugs/d' {} +
+%java_remove_annotations -p SuppressFBWarnings
```

### CODE REVIEW

**Comment by mkoncek** [comment]
The script cannot be interpreted by the current `rpmlua` present in Fedora Rawhide (version: `RPM version 4.18.0-alpha2`)
1) It complains about shebang
2) `arg` variable passing does not seem implemented so it is impossible to pass CLI args to the script.

**Comment by mizdebsk** [comment]
Why use rpmlua instead of plain lua?
Requirement on RPM 4.18 is a no-go for now, we still need to support RPM 4.14.
We can't even use RPM 4.16 features such as parametric dependency generators, or meta-requires.
Otherwise looks good.

**Comment by mizdebsk** [comment]
I've fixed CI, it should run tests once you rebase the PR.
Please remove use of rpmlua and I'll merge the PR.

**Comment by mkoncek** [comment]
I separated the functions from wrappers so that it should work with both lua and rpmlua. So that for example javapackages in Fedora Rawhide can be patched downstream to use rpmlua.
Note that `rpmlua` does not inspect paths listed in `LUA_PATH`. This can be worked around either by manually adding a line into the script before `require` clause:
```lua
package.path = package.path..";<PATH>"
```
Or by installing the library into `/usr/lib/rpm/javapackages-tools/lua/...` although I haven't tested this.

**Comment by mkoncek** [comment]
I added a bunch of commits so that they are more easily reviewed. Should I squash them later?

**Comment by mizdebsk** [comment]
There is no need to squash commits.
Merged.

**Pull request merged**
