### PR TITLE
install_pom.py: interpolate properties in current artifactId, groupId and version + add some tests

### PR DESCRIPTION
**Pull request by fridrich**
Some artifacts have things like `<artifactId>whatever_${scala.binary.version}</artifactId>`. The variable normally is defined either in the current pom or in one of its parents. When generating simplified (dependencies-only) pom, interpolate this kind of variables in the current artifact coordinates too.
This would need to be done eventually for mvn_artifact.py too. I tried but did not try a simple elegant way to do it, since the gathering of dependencies happen when the metadata artifact is already intitialized. But eventually one could create a maven artifact from the uart string, interpolate and push the 3 fields back to the metadata artifact. Or create a setter for it in the class.

### CODE REVIEW

**Comment by fridrich** [comment]
Not sure where the codecov misses come from since I added two tests. Especially them being in files I did not touch. But...

**Comment by fridrich** [comment]
> Not sure where the codecov misses come from since I added two tests. Especially them being in files I did not touch. But...

OK, now I understand, it is from my reproducible build changes from some time ago, not from this PR.

**Comment by fridrich** [comment]
Ping?

**Comment by fridrich** [comment]
ping

**Comment by fridrich** [comment]
Ping on this one

**Comment by mizdebsk** [comment]
Thanks for the ping, I will review it soon

**Comment by mizdebsk** [comment]
Looks good.

**Pull request merged**
