### PR TITLE
Add coverage report

### LINKED ISSUE #22: Test coverage reporting
It was implemented once in 493b552073477554d6be655e91bffa09ac16703c, but then reverted in 8fcf6ba0d799daf9f36083a8ca9acd38cd7b2acb because it "broke CI".
Since we moved to Travis CI, lets investigate if coverage report can be re-enabled.

### PR DESCRIPTION
**Pull request by mizdebsk**
Fixes #22

### CODE REVIEW

**Comment by mizdebsk** [comment]
Note that this only covers nosetests in test/ directory, not python/test/, that's one reason for so low coverage.
Can anyone explain me why we have two set of tests at different locations, ran in different ways?

**Comment by msimacek** [comment]
python/test/ should be unit tests for the python module
test/ are (mostly) integration tests for the macros and scripts. I'm not sure if meaningful coverage data can be generated for them, because the scripts are exec'd, sometimes even indirectly via rpmbuild

**Comment by mizdebsk** [comment]
It looks like coverage of subprocesses shouldn't be hard, http://coverage.readthedocs.io/en/coverage-4.1/subprocess.html

**Comment by mizdebsk** [comment]
> Current coverage is 87.96% (diff: 100%)

Now, that's better :)

I think this is ready to be merged. @msimacek Any further comments?

**Comment by msimacek** [comment]
Looks great, thank you :)

**Pull request merged**
